
[font]
normal                = { family = "JetBrains Mono", style = "Bold" }
size                  = 11


[cursor.style]
shape                 = "Beam"
blinking              = "Always"

[cursor.vi_mode_style]
shape                 = "Beam"
blinking              = "Off"

[window]
padding               = { x = 10, y = 15 }
opacity               = 0.9
blur                  = true
